version: '3.4'

services:

    goiar.simple.cqrs.sample.aspnetcore.rabbitmq.pub:
        image: ${DOCKER_REGISTRY-}goiarsimplecqrssampleaspnetcorerabbitmqpub
        environment:
            rabbitmq__connectionString: host=rabbitmq;username=someuser;password=1234
        depends_on:
            - goiar.simple.cqrs.sample.aspnetcore.rabbitmq.sub
        build:
            context: .
            dockerfile: sample/goiar.simple.cqrs.sample.aspnetcore.rabbitmq.pub/Dockerfile
        ports:
            - 6000:80
            - 6001:443
        networks:
            - queue-network
    
    goiar.simple.cqrs.sample.aspnetcore.rabbitmq.sub:
        image: ${DOCKER_REGISTRY-}goiarsimplecqrssampleaspnetcorerabbitmqsub
        environment:
            rabbitmq__connectionString: host=rabbitmq;username=someuser;password=1234
        build:
            context: .
            dockerfile: sample/goiar.simple.cqrs.sample.aspnetcore.rabbitmq.sub/Dockerfile
        ports:
            - 6002:80
            - 6003:443
  
networks:
    queue-network:
        name: queue-network
        driver: bridge