version: '3.4'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        #volumes:
        #    - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
        #    - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        #    - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: cookieMonster
            RABBITMQ_DEFAULT_USER: someuser
            RABBITMQ_DEFAULT_PASS: 1234
        ports:
            - 5672:5672
            - 15672:15672

    goiar.simple.cqrs.sample.aspnetcore.rabbitmq.pub:
        image: ${DOCKER_REGISTRY-}goiarsimplecqrssampleaspnetcorerabbitmqpub
        environment:
            rabbitmq__connectionString: host=rabbitmq;username=someuser;password=1234
        depends_on:
            - rabbitmq
            - goiar.simple.cqrs.sample.aspnetcore.rabbitmq.sub
        build:
            context: .
            dockerfile: sample/goiar.simple.cqrs.sample.aspnetcore.rabbitmq.pub/Dockerfile
        ports:
            - 5000:80
            - 5001:443

    goiar.simple.cqrs.sample.aspnetcore.rabbitmq.sub:
        image: ${DOCKER_REGISTRY-}goiarsimplecqrssampleaspnetcorerabbitmqsub
        environment:
            rabbitmq__connectionString: host=rabbitmq;username=someuser;password=1234
        depends_on:
            - rabbitmq
        build:
            context: .
            dockerfile: sample/goiar.simple.cqrs.sample.aspnetcore.rabbitmq.sub/Dockerfile
        ports:
            - 5002:80
            - 5003:443
